# Generated by Django 5.2.16 on 2026-08-17 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Algoritmo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
                ('parametros', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Algoritmo',
                'verbose_name_plural': 'Algoritmos',
                'db_table': 'algoritmo',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('senha_hash', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nomeArquivo', models.CharField(db_column='nomeArquivo', max_length=255, verbose_name='Nome do Arquivo')),
                ('formato', models.CharField(max_length=50, verbose_name='Formato')),
                ('resolucao', models.CharField(max_length=50, verbose_name='Resolução')),
                ('tamanho', models.FloatField(help_text='Tamanho do arquivo em KB ou MB', verbose_name='Tamanho')),
                ('dadosOriginal', models.BinaryField(db_column='dadosOriginal', verbose_name='Dados Original (Blob)')),
                ('dadosProcessada', models.BinaryField(blank=True, db_column='dadosProcessada', null=True, verbose_name='Dados Processada (Blob)')),
                ('algoritmo', models.ForeignKey(blank=True, db_column='algoritmo_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imagens', to='models.algoritmo', verbose_name='Algoritmo')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='models.usuario', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Imagem',
                'verbose_name_plural': 'Imagens',
                'db_table': 'imagem',
            },
        ),
    ]
