# Generated by Django 5.2.16 on 2026-08-18 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='token_versao',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Versão do Token Ativo'),
        ),
    ]
