# Generated by Django 5.2.17 on 2026-08-18 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagem',
            options={'ordering': ['-id'], 'verbose_name': 'Imagem', 'verbose_name_plural': 'Imagens'},
        ),
        migrations.AddField(
            model_name='imagem',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em'),
        ),
    ]
