# Generated by Django 5.2.17 on 2026-08-19 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_alter_imagem_options_imagem_criado_em'),
        ('models', '0002_usuario_token_versao'),
    ]

    operations = [
    ]
